apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: airport-service
build:
  googleCloudBuild:
    projectId: aviralmansingka-pulumi-gke
    gradleImage: gradle:7.5.1-jdk17
  artifacts:
    - image: gcr.io/aviralmansingka-pulumi-gke/airport-service
      jib: {}
deploy:
  kubectl:
    manifests:
      - manifests/*
