apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: airport-service
build:
  googleCloudBuild:
    projectId: aviralmansingka-pulumi-gke
  artifacts:
    - image: gcr.io/aviralmansingka-pulumi-gke/airport-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/spring-boot
deploy:
  kubectl:
    manifests:
      - manifests/*
portForward:
  - resourceType: service
    resourceName: airport-service
    port: 8080
