apiVersion: v1
kind: ConfigMap
metadata:
  name: airport-service
data:
  application.yaml: |-
    spring:
      config:
        activate:
          on-profile: default
    eureka:
      instance:
        # enable to register multiple app instances with a random server port
        instance-id: ${spring.application.name}:${random.uuid}

    airport: KMAH

    test.message: inside ConfigMap

    fbo:
      fuel: 100LL
